AirBench/Models/Bench.cs
using System.ComponentModel.DataAnnotations;

namespace AirBench.Models
{
    public class Bench
    {
        public int Id { get; set; }
        [Required]
        public decimal Rating { get; set; }
        [Required, MaxLength(255)]
        public string Description { get; set; }
        [Required]
        public int Seats { get; set; }
        [Required]
        public decimal Latitude { get; set; }
        [Required]
        public decimal Longitude { get; set; }

        public int PosterId { get; set; }
        public User Poster { get; set; }
    }
}

AirBench/Controllers/BenchController.cs
using AirBench.Data;
using AirBench.FormModels;
using AirBench.Models;
using AirBench.Repositories;
using System.Web.Mvc;

namespace AirBench.Controllers
{
    public class BenchController : Controller
    {
        // GET: Bench
        private Context context;

        public BenchController()
        {
            context = new Context();
        }

        public ActionResult Index(int id)
        {
            var repository = new BenchRepository(context);
            Bench bench = repository.GetBenchById(id);
            return View(bench);
        }

        [Authorize]
        [HttpGet]
        public ActionResult Create(decimal? lat, decimal? lon)
        {
            var bench = new CreateBench();
            if(lat != null)
            {
                bench.Latitude = lat.Value;
                bench.Longitude = lon.Value;
            }
            return View(bench);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateBench bench)
        {
            BenchRepository benchRepository = new BenchRepository(context);
            if (ModelState.IsValidField("Description"))
            {
                Bench newBench = new Bench(0, bench.Description,
                bench.Seats, bench.Latitude, bench.Longitude);

                User user = new UserRepository(context).GetLoggedInUser(User.Identity.Name);
                newBench.Poster = user;
                newBench.PosterId = user.Id;

                benchRepository.Insert(newBench);
                return RedirectToAction("Index", "Home");
            }
            return View(bench);
        }
    }
}

AirBench/Controllers/ReviewController.cs
using AirBench.Data;
using AirBench.FormModels;
using AirBench.Models;
using AirBench.Repositories;
using System.Web.Mvc;

namespace AirBench.Controllers
{
    [Authorize]
    public class ReviewController : Controller
    {
        private Context context;

        public ReviewController()
        {
            context = new Context();
        }

        // GET: Review
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Create(int id)
        {
            CreateReview review = new CreateReview();
            return View(review);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CreateReview review, int id)
        {
            if (ModelState.IsValidField("Description"))
            {
                var reviewRepository = new ReviewRepository(context);
                var benchRepository = new BenchRepository(context);

                Review newReview = new Review(0, review.Rating, review.Decription);

                Bench bench = benchRepository.GetBenchById(id);
                bench.Reviews.Add(newReview);
                bench.CalculateRating(bench.Reviews);

                newReview.Bench = bench;
                newReview.BenchId = id;

                User user = new UserRepository(context).GetLoggedInUser(User.Identity.Name);
                newReview.Poster = user;
                newReview.PosterId = user.Id;

                reviewRepository.Insert(newReview);
                return RedirectToRoute("Default", new { controller = "Bench", action = "Index", id = id });
            }
            return View(review);
        }
    }
}

AirBench/Views/Bench/Create.cshtml
@model AirBench.FormModels.CreateBench

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Bench", FormMethod.Post, new { id = "CreateBenchForm" }))
{
    @Html.AntiForgeryToken()
    
    @Html.ValidationSummary()
    <div>
        @Html.LabelFor(m => m.Description)
        @Html.TextBoxFor(m => m.Description)
    </div>

    <div>
        @Html.LabelFor(m => m.Seats)
        @Html.TextBoxFor(m => m.Seats)
    </div>

    <div>
        @Html.LabelFor(m => m.Latitude)
        @Html.TextBoxFor(m => m.Latitude)
    </div>

    <div>
        @Html.LabelFor(m => m.Longitude)
        @Html.TextBoxFor(m => m.Longitude)
    </div>

    <div>
        <button type="submit" id="createButton" disabled>Login</button>
    </div>
 

}

<div>
    @Html.ActionLink("Back to List", "Index", "Home")
</div>

<script src="~/scripts/button.js"></script>

AirBench/Views/Bench/Index.cshtml
@model AirBench.Models.Bench

@{
    ViewBag.Title = "Index";
}

<h2>@Model.Id</h2>

<table>
    <tr>
        <th>Bench No.</th>
        <th>Rating</th>
        <th>Description</th>
        <th>Seats</th>
        <th>Latitude</th>
        <th>Longitude</th>
        <th></th>
    </tr>

    <tbody>
        <tr>
            <td>@Model.Id</td>
            @if(Model.Reviews.Count == 0)
            {
                <td>No Ratings</td>
            }
            else
            {
                <td>@Model.Rating</td>
            }
            <td>@Model.Description</td>
            <td>@Model.Seats</td>
            <td>@Model.Latitude</td>
            <td>@Model.Longitude</td>
        </tr>  
    </tbody>
</table>

<h3>Reviews</h3>

@if(Model.Reviews.Count == 0)
{
    <p>No Reviews Yet</p>
}
else
{
    <table>
        <tr>
            <th>Rating</th>
            <th>Description</th>
            <th>Posted</th>
            <th>Poster</th>
        </tr>

        <tbody>
            @foreach (var review in Model.Reviews)
            {
                <tr>
                    <td>@review.Rating</td>
                    <td>@review.Description</td>
                    <td>@review.postDate</td>
                    <td>@review.Poster.FirstName @review.Poster.LastName[0]</td>
                </tr>
            }
        </tbody>
    </table>
}

@Html.ActionLink("Leave a review", "Create", "Review", new { id = Model.Id }, new { @class = "btn btn-info" })